<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFYgEUl1\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFYgEUl1/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerFYgEUl1.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerFYgEUl1\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerFYgEUl1\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'FYgEUl1',
    'container.build_id' => '63ef317b',
    'container.build_time' => 1556034578,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFYgEUl1');
